### ISSUE TITLE
Manifests are broken.

### ISSUE THREAD

**Issue by anovstrup** [scalagwt/scalagwt-scala#6]
For example, ClassManifest.newArray throws a RuntimeException.

**Comment by anovstrup** [comment]
Greg, I know you're already aware of this issue, but I needed a URI to refer to in code comments. :)

**Comment by gkossakowski** [comment]
Sure, we should have a ticket for it. Manifests are particularly tricky to support because their JVM-based implementation requires reflection that GWT doesn't support.

Lex and me discussed some ideas how to solve this problem but I didn't have a chance to sit down and write a prototype yet. If this turns out to be a very serious roadblock then I'll prioritize work on it. Otherwise, this is on my todo list which is not that long.

**Comment by gkossakowski** [comment]
Discussed here: https://groups.google.com/d/topic/scalagwt/przy_I1ApRU/discussion

Will be trying to tackle this as described here: https://groups.google.com/d/msg/scalagwt/przy_I1ApRU/dBdlV0ijKUMJ

**Comment by gkossakowski** [comment]
Problem with Manifests is largely solved. Closing this issue.
